controller_manager:
  ros__parameters:
    update_rate: 10 # hz

    joint_state_broadcaster: 
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_links_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - bicep_joint
          - arm1_joint
          - arm2_joint

        command_interfaces:
          - position

        state_interfaces:
          - position

        open_loop_control: true
        allow_integration_in_goal_trajectories: true

    gripper_controller:
      # type: joint_trajectory_controller/JointTrajectoryController
      type: forward_command_controller/ForwardCommandController
      ros__parameters:
        joints:
          - leftClaw_joint
        interface_name: position


