default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits: 
  bicep_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: -5.0 
  arm1_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: -5.0
  arm2_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: -5.0
  leftClaw_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: -5.0
  rightClaw_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    max_deceleration: -5.0
